# ansible-galaxy collection install community.general
- name: My first play
  hosts: all
  tasks:
    - name: Set git username
      community.general.git_config:
        name: user.name
        value: Gennadiy Polezhaev
      become: true
    - name: Set git username email
      community.general.git_config:
        name: user.email
        value: gpolejaev@gmail.com
      become: true
