# ansible-galaxy collection install community.general
- name: My first play
  hosts: all
  tasks:
    - name: name
      git_config:
        name: user.name
        value: Gennadiy Polezhaev
      become: true
    - name: email
      git_config:
        name: user.email
        value: gpolejaev@gmail.com
      become: true
      