---
- name: Playbook for Ingress controller installation.
  hosts: all
  become: true
  gather_facts: true
  vars:
    hosts_file_ips: |
      10.0.1.8  storage lb.local
      10.0.1.9  master lb.local
      10.0.1.10 node-10 lb.local
      10.0.1.11 node-11 lb.local

  tasks:
    - name: Create enties in hosts
      ansible.builtin.blockinfile:
        state: present
        path: /etc/hosts
        block: "{{ hosts_file_ips }}"

    - name: Install Ingress controller
      # https://kubernetes.github.io/ingress-nginx/deploy/baremetal/
      become: false
      when: inventory_hostname == 'master'
      ansible.builtin.command: >-
        helm upgrade --install ingress-nginx ingress-nginx \
        --repo https://kubernetes.github.io/ingress-nginx \
        --namespace ingress-nginx --create-namespace
      changed_when: output.rc == 0
