---
- name: Playbook for k8s install prerequisites
  hosts: master
  become: false
  gather_facts: false
  tasks:
    - name: Install Helm
      become: false
      ansible.builtin.shell: |-
        set -o pipefail
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo \
          tee /usr/share/keyrings/helm.gpg > /dev/null
        sudo apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) \
          signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ \
          all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm -y > helm-installation-log
        helm repo add bitnami https://charts.bitnami.com/bitnami
      args:
        chdir: $HOME
        creates: helm-installation-log.txt

    - name: Install Nginx Ingress controller
      become: false
      ansible.builtin.command: >-
        helm upgrade --install ingress-nginx ingress-nginx
        --repo https://kubernetes.github.io/ingress-nginx
        --namespace ingress-nginx --create-namespace
      args:
        chdir: $HOME
        creates: helm-installation-log.txt
