---
- name: Playbook for k8s install prerequisites
  hosts: all
  become: true
  gather_facts: true
  vars:
    packages_for_install:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https
      # - net-tools

  tasks:
    - name: Play to set time
      block:
        - name: Set timezone
          community.general.timezone:
            name: Europe/Moscow
          register: timeset_result

        - name: Restart cron service
          ansible.builtin.service:
            name: cron
            state: restarted
          when: timeset_result.changed

    - name: Play to fill k8s cluster CRI prerequisites
      block:
        - name: Remove swapfile
          ansible.posix.mount:
            path: swap
            fstype: swap
            state: absent
            backup: true

        - name: Create enties in hosts
          ansible.builtin.blockinfile:
            state: present
            path: /etc/hosts
            block: |
              10.0.1.9  master
              10.0.1.10 node-10
              10.0.1.11 node-11

        - name: Prerequisite /etc/modules-load.d/k8s.conf
          ansible.builtin.blockinfile:
            path: /etc/modules-load.d/k8s.conf
            mode: '644'
            create: true
            state: present
            block: |
              overlay
              br_netfilter

        - name: Prerequisite load kernel modules
          community.general.modprobe:
            name: "{{ item }}"
            state: present
          loop:
            - overlay
            - br_netfilter

        - name: Prerequisite /etc/sysctl.d/k8s.conf
          ansible.builtin.blockinfile:
            path: /etc/sysctl.d/k8s.conf
            mode: '644'
            create: true
            state: present
            block: |
              net.bridge.bridge-nf-call-iptables = 1
              net.bridge.bridge-nf-call-ip6tables = 1
              net.ipv4.ip_forward = 1

        # Define kernel variables and set in runtime
        - name: Prerequisite sysctl conf load
          ansible.posix.sysctl:
            name: "{{ item.key }}"
            value: "{{ item.value }}"
            sysctl_set: true
          with_dict:
            net.bridge.bridge-nf-call-iptables: 1
            net.bridge.bridge-nf-call-ip6tables: 1
            net.ipv4.ip_forward: 1

        # Update the apt package index and install packages to allow apt to use a
        # repository over HTTPS
        - name: Install prerequisites packages
          ansible.builtin.apt:
            update_cache: true
            name: "{{ packages_for_install }}"

        - name: Add Docker GPG apt Key
          ansible.builtin.apt_key:
            url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
            state: present

        - name: Add docker repository to apt
          ansible.builtin.apt_repository:
            repo: >
              deb https://download.docker.com/linux/{{ ansible_distribution | lower }}
              {{ ansible_distribution_release }} stable
            state: present

        - name: Install containerd.io
          ansible.builtin.apt:
            update_cache: true
            name: containerd.io=1.6.14-1
            # name: containerd.io=1.6.12-1
            state: present

        - name: Create directory for kubectl config
          ansible.builtin.file:
            path: /etc/containerd
            state: directory
            mode: '755'

        - name: Create containerd config
          ansible.builtin.shell: |
              containerd config default > /etc/containerd/config.toml
          register: my_output
          changed_when: my_output.rc == 0

        - name: Configure containerd so that it starts using systemd as cgroup
          ansible.builtin.lineinfile:
            path: /etc/containerd/config.toml
            regexp: 'SystemdCgroup = false'
            line: SystemdCgroup = true

        - name: Restart containerd service
          ansible.builtin.service:
            name: containerd
            state: restarted

    - name: Play to install kubelet, kubeadm and kubectl
      block:
        - name: Add Google Cloud public signing key
          ansible.builtin.apt_key:
            url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
            state: present

        - name: Add the Kubernetes apt repository
          ansible.builtin.apt_repository:
            repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
            state: present

        - name: Install kubelet, kubeadm and kubectl
          ansible.builtin.apt:
            name:
              - kubelet=1.26.0-00
              - kubeadm=1.26.0-00
              - kubectl=1.26.0-00
            update_cache: true
            state: present

        - name: Prevent packages from being upgraded
          ansible.builtin.dpkg_selections:
            name: "{{ item }}"
            selection: hold
          loop:
            - kubelet
            - kubeadm
            - kubectl

        - name: Pulls the images for Kubernetes
          ansible.builtin.shell: >-
            sudo kubeadm config images pull --image-repository=registry.k8s.io
            --cri-socket unix:///run/containerd/containerd.sock
            >> k8s-images-download-output.txt
          args:
            chdir: $HOME
            creates: k8s-images-download-output.txt

    - name: Play to create cluster with kubeadm on control nodes
      when: inventory_hostname in groups['master_nodes']
      become: false
      block:
        - name: Create cluster kubeadm init
          become: true
          # Обязательные только эти параметры:
          # --apiserver-advertise-address=10.0.1.9
          # --pod-network-cidr=10.32.0.0/12
          ansible.builtin.shell: >-
            sudo kubeadm init --apiserver-advertise-address=10.0.1.9
            --pod-network-cidr=10.32.0.0/12
            --control-plane-endpoint=10.0.1.9
            --upload-certs
            --cri-socket unix:///run/containerd/containerd.sock
            >> cluster-init-output.txt
          args:
            chdir: $HOME
            creates: cluster-init-output.txt

        - name: Create directory for kubectl config
          ansible.builtin.file:
            path: $HOME/.kube
            state: directory
            mode: '775'

        - name: Configure kubectl interract with cluster
          ansible.builtin.shell: |
            sudo cp -n /etc/kubernetes/admin.conf $HOME/.kube/config \
            >> kube-config-for-kubectl.txt
            sudo chown $(id -u):$(id -g) $HOME/.kube/config
          args:
            chdir: $HOME
            creates: kube-config-for-kubectl.txt

        - name: Install Weave CNI Add-on
          ansible.builtin.shell: >-
            kubectl apply -f
            https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
            >> weave-cni-cinfig.txt
          args:
            chdir: $HOME
            creates: weave-cni-cinfig.txt

        - name: Save token to join cluster
          ansible.builtin.command: kubeadm token create --print-join-command
          register: token
          changed_when: token.rc != 0

    - name: Join nodes to cluster
      when: inventory_hostname in groups['worker_nodes']
      ansible.builtin.command: "{{ hostvars.master.token.stdout }}"
      register: output
      changed_when: output.rc == 0
