---
- name: Install and configure softaware on Vagrant machines
  hosts: all
  become: true
  tasks:
    - name: Install git
      ansible.builtin.package:
        name:
          - jq
          - git
        state: present
      when: ansible_facts['os_family'] == "Debian"
      register: facts
    - name: Echo
      ansible.builtin.debug:
        var: facts
...
