- name: Playbook for changing local mac settings
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Bash auto-complete for k8s
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        block: |
          # kubectl auto-complete
          stty -ixon
          alias k="kubectl"
          source <(kubectl completion bash)
          complete -o default -F __start_kubectl k

          # Aliases for convenience
          alias h='history'
          alias ll='ls -laG'

    - name: Settings for Vim
      ansible.builtin.blockinfile:
        path: /etc/vim/vimrc
        # for Ubuntu
        block: |
          unlet! skip_defaults_vim
          source $VIMRUNTIME/defaults.vim
          set number
