---
- name: Playbook for k8s install prerequisites
  hosts: master
  become: true
  gather_facts: false
  vars:
    containerd_version: "1.6.14-1"
  tasks:
    - name: Pull an image
      community.docker.docker_image:
        name: pacur/centos-7
        source: pull

