- name: Temp playbook for test purpoces
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Debug
      ansible.builtin.debug:
        msg: >
          {{
          ansible_all_ipv4_addresses[0] | quote }}
