- name: Temp playbook for test purpoces
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Set timezone
      community.general.timezone:
        name: Europe/Moscow
      register: result

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ result.changed }}"

    - name: Restart containerd service
      ansible.builtin.service:
        name: cron
        state: restarted
      when: result.changed
