- name: Temp playbook for test purpoces
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Connect Weave Net CNI add on
      ansible.builtin.command: >
        kubectl apply -f
        https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
      register: output
      changed_when: output.rc == 0
