- name: Temp playbook for test purpoces
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install prerequisites utils
      ansible.builtin.apt:
        update_cache: true
        name: "{{ packages_for_install }}"
