- name: Temp playbook for test purpoces
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Create directory for kubectl config
      become: false
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: '775'

    - name: Configure kubectl interract with cluster
      become: false
      ansible.builtin.shell: |
        sudo cp -n /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
      when: inventory_hostname in groups['master_nodes']
      register: my_output
      changed_when: my_output.rc == 0
