---
- name: Save the result of setup module to register var and echo it next step
  hosts: all
  tasks:
    - name: Save setup to register
      ansible.builtin.setup:
      register: master_facts
    - name: Echo result
      ansible.builtin.debug:
        var: inventory_hostname
...
